### ISSUE TITLE
Which part of Sweden do you live in?

### ISSUE THREAD

**Issue by LinusU** [kevva/ama#18]

**Comment by kevva** [comment]
I live in Borås, which is located nearby Gothenburg in the western part of Sweden. In the house to the right in this picture https://www.google.se/maps/place/fristadsv%C3%A4gen+102b+google+maps/@57.7492179,12.945297,3a,75y,121.62h,90t/data=!3m4!1e1!3m2!1sbIQFWFC3Xh6-b3IlAF4gtg!2e0!4m2!3m1!1s0x0:0x4365d0150985addb?sa=X&ved=0CCQQxB0wAGoVChMItvm78sGNxwIVBBUsCh1xZwSy.
