### ISSUE TITLE
What font did you use for your brightness module?

### ISSUE THREAD

**Issue by hackergrrl** [kevva/ama#3]
I dig it! (see https://github.com/kevva/brightness)

Secondary: what tool(s) did you use? Inkscape?

**Comment by gillstrom** [comment]
@sindresorhus

**Comment by sindresorhus** [comment]
@noffle I made the logo, so probably better to move this to https://github.com/sindresorhus/ama

**Comment by hackergrrl** [comment]
My err. See sindresorhus/ama#134.
