### ISSUE TITLE
How much money do you have?

### ISSUE THREAD

**Issue by hafffe** [kevva/ama#5]
Asking cuz Sindre got same question!

**Comment by kevva** [comment]
![](https://cloud.githubusercontent.com/assets/709159/8597205/511211d4-2654-11e5-8d03-cf61dda5d15d.png)

I'll try to give a transparent answer like @sindresorhus did. It's like $20k that I've earned mostly doing freelance work. I should really get a savings account though.

**Comment by gillstrom** [comment]
Yeah, it's hard to change the amount with dev tools..

**Comment by hafffe** [comment]
And maybe blur you account number to ;)
